# Generated by Django 2.0.2 on 2019-12-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duizhao',
            fields=[
                ('宠物编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('宠物名字', models.CharField(blank=True, max_length=100)),
                ('宠物价值', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='huancun',
            fields=[
                ('唯一键', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('账号编号', models.CharField(max_length=100)),
                ('石头数量', models.CharField(blank=True, max_length=100)),
                ('等级', models.CharField(blank=True, max_length=100)),
                ('宠物', models.TextField()),
                ('是否上传', models.CharField(default='否', max_length=2)),
                ('更新时间', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shujuku',
            fields=[
                ('账号编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('石头数量', models.CharField(blank=True, max_length=100)),
                ('等级', models.CharField(blank=True, max_length=100)),
                ('更新时间', models.DateTimeField(auto_now=True)),
                ('宠物', models.TextField()),
                ('已卖', models.CharField(default='是', max_length=20)),
                ('买家', models.CharField(blank=True, max_length=100)),
                ('价格', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hot',
            name='number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
