# Generated by Django 2.0.2 on 2020-01-09 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='duizhao',
            fields=[
                ('宠物编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('宠物名字', models.CharField(blank=True, max_length=100)),
                ('宠物价值', models.CharField(blank=True, max_length=100)),
                ('加入时间', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='shujuku',
            fields=[
                ('账号编号', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('石头数量', models.CharField(blank=True, max_length=100)),
                ('等级', models.CharField(blank=True, max_length=100)),
                ('更新时间', models.CharField(blank=True, max_length=100)),
                ('宠物', models.TextField()),
                ('已卖', models.CharField(default='是', max_length=20)),
                ('买家', models.CharField(blank=True, max_length=100)),
                ('价格', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='hot',
            name='number',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
