# Generated by Django 2.0.2 on 2020-01-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200114_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shujuku',
            name='已卖',
            field=models.CharField(default='否', max_length=20),
        ),
        migrations.AlterField(
            model_name='shujuku',
            name='石头数量',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
