# Generated by Django 2.0.2 on 2020-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200115_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='shujuku',
            name='账号ID',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
